### ISSUE TITLE
Wagtail 5.0 Upgrade

### ISSUE THREAD

**Issue by nickmoreton** [torchbox-forks/wagtailquickcreate#1]
Pull in any other work currently not merged

**Comment by nickmoreton** [comment]
The Wagtail 4.2 PR is here: https://github.com/kevinhowbrook/wagtailquickcreate/pull/24 from branch: https://github.com/nickmoreton/wagtailquickcreate/tree/support/wagtail42

**Comment by nickmoreton** [comment]
Wagtail 5 upgrade PR is here: https://github.com/kevinhowbrook/wagtailquickcreate/pull/25

**Comment by katdom13** [comment]
The upstream PR has been merged and this can be closed.
